include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    require_trailing_commas: false
    always_put_required_named_parameters_first: false
    avoid_redundant_argument_values: false
    prefer_double_quotes: false
    prefer_single_quotes: false
    unnecessary_lambdas: false
    avoid_print: false
    use_build_context_synchronously: false
    directives_ordering: false
    sort_pub_dependencies: false
    avoid_dynamic_calls: false
    sort_child_properties_last: false
    sort_constructors_first: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false