// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ma1D0Hi6TJ_kIMnImWCM2jpFQCSIidY',
    appId: '1:134344035709:web:076b8e6627fd45dde11014',
    messagingSenderId: '134344035709',
    projectId: 'app-maps-73439',
    authDomain: 'app-maps-73439.firebaseapp.com',
    storageBucket: 'app-maps-73439.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTmvqY1EBFcNBUr4JKDPromUSd8GFg78',
    appId: '1:134344035709:android:77488c26d4755025e11014',
    messagingSenderId: '134344035709',
    projectId: 'app-maps-73439',
    storageBucket: 'app-maps-73439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZSpWBIJkByT82gPiDBQmIk3kiAc0f-A',
    appId: '1:134344035709:ios:160ae620021d9dbce11014',
    messagingSenderId: '134344035709',
    projectId: 'app-maps-73439',
    storageBucket: 'app-maps-73439.appspot.com',
    iosBundleId: 'kh.com.aditi.ebc.driver.app',
  );
}
