include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    always_put_required_named_parameters_first: false
    public_member_api_docs: false
    avoid_dynamic_calls: false
    always_use_package_imports: false
    constant_identifier_names: false
